### ISSUE TITLE
Formalize Merkato bot operation

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#10]
Tentative proposal:

Assumption: Once a Merkato bot holds the mutex for a pair+exchange, nothing else makes trades there.

1. Get all parameters from user.
2. Place bid and ask ladders. 
3. Record positions of all bids and asks in database. 
4. Give the Exchange object that placed the ladders the mutex for that pair+exchange.
5. Periodically poll for new transactions
6. When a new transaction is detected:
    7. Check if an order is on the books that isn't in your database
    8. If not, put a corresponding order there, and place an entry in your database
    9. If so, put an entry in your database

This is going to need a Merkato class as well, which is associated with a config. Merkato objects hold a mutex (exchange+pair), trade history, and current orderbook state.

**Comment by nasaWelder** [comment]
Why are open orders in database? If it's for persistence, I'd store ladder settings, then on reboot, just query the exchange for open orders. Thanks we do won't know itself if the order gets filled, so wouldn't it almost always be stale data?

**Comment by needmoney90** [comment]
Should be mostly done
