### ISSUE TITLE
Figure out log level scale

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#102]
What does a priority 1-100 mean in our scale?

**Comment by nasaWelder** [comment]
I'm sure no more than 10 levels are necessary but at least it's granular. It's really a verbosity setting. nothing would print at level 0, if user wanted super quiet. Errors and headings would be level 1 ish. Level 2 could show what function's being called, 3 its result, 4 and 5 for sub-functions therein. Defaulting to 100 just says show me everything.

**Comment by needmoney90** [comment]
Ok, we can do 0-100 where 0 is nothing, 100 is everything, increments of 10 per level.

Or 1-10, and 100 for all?
