### ISSUE TITLE
Allow querying of available balance for a user

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#113]
This is equal to total balance minus reserved balances. Requires #112

**Comment by mark-antony1** [comment]
We need to decide a few things,
1. What affects the reserve balance for a merkato
  a. when do we update the reserve balance on the merkato object and persist this in the DB
2. Is this tux specific? For Example, when I place an order on GDAX as follows
   a. I have $100, 0 BTC and place an order for $100 worth of bitcoin my balance goes to $0 and 0 BTC.
       When I cancel the order, my balance goes to $100, if the order confirms, I obviously get BTC
   b. Would this process affect the values returned from querying?

**Comment by needmoney90** [comment]
1. Reserve balance is affected when a merkato is first created, when a user adds/removed BTC/alt to a particular merkato, when the price approaches an undistributed region (and some reserve must be distributed), and when a merkato is shut off.
1a. all those points

2. We assume the user only buys/sells/withdraws through our interface during its operation. We will prevent them from drawing down below the sum of all reserves, and force them to take it from a particular merkato.

**Comment by mark-antony1** [comment]
I don't believe we currently have a way to track user balances outside of a merkato, I guess we will need a lot of querying?

Also, we dont have a way to add or remove BTC or an alt, do we?

**Comment by mark-antony1** [comment]
We need a function to query all merkatos in the DB that belong to a particular exchange, with a particular private key, and total all the tokens held in merkatos (denominated by bid_budget and ask_budget)... Then we need to query the exchange api to get all value held in that exchange from the exchange's servers, and compare the totaled merkato assets compared to the exchange's assets.

Thoughts?

**Comment by needmoney90** [comment]
> I don't believe we currently have a way to track user balances outside of a merkato, I guess we will need a lot of querying?

> Also, we dont have a way to add or remove BTC or an alt, do we?

Correct on both counts. 

> We need a function to query all merkatos in the DB that belong to a particular exchange, with a particular private key, and total all the tokens held in merkatos (denominated by bid_budget and ask_budget)... Then we need to query the exchange api to get all value held in that exchange from the exchange's servers, and compare the totaled merkato assets compared to the exchange's assets.

Yup. My only concern is the repeated usage/comparison of the private key, but I'm not sure we can dispense with that with how all requests need signing, so it doesn't really matter.

**Comment by mark-antony1** [comment]
We do need a solution to the private key. Very easily could become a large hotwallet.

**Comment by needmoney90** [comment]
Most exchanges have the ability to restrict withdrawals from the api keys, but we need some way to make sure users don't draw down below reserves. I guess we could place reserves absurdly high or low on the books, but that carries its own problems

**Comment by needmoney90** [comment]
Also that doesn't prevent the 'buy high sell low' way to transfer assets on an exchange when withdrawals are restricted

**Comment by mark-antony1** [comment]
is this complete?

**Comment by nasaWelder** [comment]
This would be simple, for a beta version, if we just make budget a user supplied init parameter. We've kind of gotten lost in the weeds in feature creep. 

Let's get the trading started, then we can bolt on a budget aware object. I have some ideas on that.

**Comment by needmoney90** [comment]
I believe this is complete. Can reopen if we have issues.
