### ISSUE TITLE
Inserting a merkato/exchange with the same UUID as an existing one

### ISSUE THREAD

**Issue by mark-antony1** [needmoney90/merkato#125]
decide how we will handle replacement or rejection when trying to insert an already present exchang/merkato into the db

**Comment by nasaWelder** [comment]
the use case is when user needs to update the api keys to existing config

**Comment by needmoney90** [comment]
you use the UPDATE command as opposed to INSERT, I believe

**Comment by nasaWelder** [comment]
Sounds like update should be used instead of insert... Always

**Comment by mark-antony1** [comment]
Update will not create a new row if there is not already a merkato/exchange the same UUID

**Comment by mark-antony1** [comment]
this should be solved @livinginformation
