### ISSUE TITLE
Context stuff

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#127]
https://github.com/livinginformation/merkato/blob/1bc410f5dcbd623531ca214971bd48c546591770/merkato/merkato.py#L349

Hey nasa, the bought and sold variables - What format do you need those in?

**Comment by nasaWelder** [comment]
A la

"filled_orders" :  {"buy" : [(0.022, 0.5, "2016-08-26 18:53:38"), 
                             (0.018, 1.5, "2016-08-26 18:53:38") ],
                    "sell"  : [(0.027, 0.5 ,"2016-08-26 18:53:38"), 
                              (0.033,1.5, "YYYY-MM-DD HH:MM:SS") ]},

**Comment by nasaWelder** [comment]
Looks like list of tuples (price, amount, datetimestring)

**Comment by nasaWelder** [comment]
Negotiable, I guess.

**Comment by needmoney90** [comment]
Why do they need to be in separate arrays? Can they be interlaced?

**Comment by needmoney90** [comment]
so, why is there a bought and sold array in the first place?

**Comment by nasaWelder** [comment]
It was arbitrary when I started the GUI. either merkato can sort it can sort it or the gui can. Just needs to be the same no matter what exchange the info is coming from

**Comment by needmoney90** [comment]
https://github.com/livinginformation/merkato/issues/131

**Comment by needmoney90** [comment]
https://github.com/livinginformation/merkato/pull/132

I've modified it to return a single array containing all new orders there. You were right, it was previously returning the entire history, it is now culled down.

**Comment by nasaWelder** [comment]
@livinginformation what is the format of get_my_open_orders ? need it for that part of context in GUI

**Comment by nasaWelder** [comment]
close
