### ISSUE TITLE
Merkato init

### ISSUE THREAD

**Issue by nasaWelder** [needmoney90/merkato#129]
There are two init cases, new and recovery. Neither are coded.

**Comment by mark-antony1** [comment]
I don't understand, can you explain more?

**Comment by nasaWelder** [comment]
Instantiating a mekato doesn't do anything, it needs to set itself up so it's ready for self.update_order_book() to be called at anytime after that call. 

All the GUI will do is instantiate them all and run update_order_book every ten seconds on all of them.

It needs to either decide it needs to do nothing since the orders are already placed (recovery) or make the ladders (new)

**Comment by needmoney90** [comment]
https://www.draw.io/#G1qM1aJ4RaiH71KaoH9dmzBgDhr5sCAM6h

we're making a flowchart currently of expected operation
