### ISSUE TITLE
Buys and sells should be interlaced

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#131]
https://github.com/livinginformation/merkato/blob/a75fcece4daeb6522bb36eeb554a5c44125153e3/graph.py#L372

You have separate buys and sells for this data, tux provides it as interlaced (one array, buys and sells one after the other). I expect other exchanges provide this data interlaced as well. This should be switched to consume in the interlaced format.

```
[{'id': '430236', 'date': '2018-05-30 17:03:41', 'type': 'buy', 'price': '0.00000290', 'amount': '78275.86206896', 'total': '0.22700000', 'fee': '0.00000000', 'feepercent': '0.000', 'orderId': '86963799', 'market': 'BTC', 'coin': 'PEPECASH', 'market_pair': 'BTC_PEPECASH'}, {'id': '430238', 'date': '
2018-05-30 17:03:41', 'type': 'buy', 'price': '0.00000289', 'amount': '78546.71280277', 'total': '0.22700000', 'fee': '0.00000000', 'feepercent': '0.000', 'orderId': '86963798', 'market': 'BTC', 'coin': 'PEPECASH', 'market_pair': 'BTC_PEPECASH'}, {'id': '430242', 'date': '2018-05-30 17:03:41', 'type
': 'buy', 'price': '0.00000288', 'amount': '78819.44444444', 'total': '0.22700000', 'fee': '0.00000000', 'feepercent': '0.000', 'orderId': '86963797', 'market': 'BTC', 'coin': 'PEPECASH', 'market_pair': 'BTC_PEPECASH'},{'id': '423240', 'date': '2018-04-22 06:19:19', 'type': 'sell', 'price
': '0.00000500', 'amount': '6711.95200000', 'total': '0.03355976', 'fee': '0.00000000', 'feepercent': '0.000', 'orderId': '90404882', 'market': 'BTC', 'coin': 'PEPECASH', 'market_pair': 'BTC_PEPECASH'},...]
```

**Comment by nasaWelder** [comment]
That's fine. Can you put the format in a comment in that function

**Comment by nasaWelder** [comment]
@livinginfirmation can u confirm it will only have new fills, and not all fills.

**Comment by needmoney90** [comment]
Can confirm it will only have new fills.

> Can you put the format in a comment in that function

https://github.com/livinginformation/merkato/blob/master/graph.py#L373

**Comment by needmoney90** [comment]
Please make a note of that in the GUI code that the input is only new fills (just for clarity's sake)

**Comment by nasaWelder** [comment]
close
