### ISSUE TITLE
Logo design for frostwire

### ISSUE THREAD

**Issue by leonardoderoy** [needmoney90/merkato#226]
Hello! @livinginformation

I'm a graphic designer and I like to support your project because I'm always downloading movies and stuff so I really liked this project, also i'm an open source enthusiast. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Leonardo Deroy

Graphic Designer

**Comment by needmoney90** [comment]
This is not Frostwire

**Comment by leonardoderoy** [comment]
Sorry for the misunderstanding, if you are interested in the logo you could provide me with all the information about your project and what it is about.
Thank you @livinginformation

**Comment by needmoney90** [comment]
This is a market making bot for cryptocurrencies.
