### ISSUE TITLE
bot’s update method returns relavant data for GUI

### ISSUE THREAD

**Issue by nasaWelder** [needmoney90/merkato#25]
Since the bot uses this info in its calculations, it should just return it. Should be standard across different bot types.

I.e.
Open orders
Closed orders
Balances
Market price or lowest highest ask/bid
Etc

**Comment by needmoney90** [comment]
Would you like it in one package, or individual functions?

**Comment by nasaWelder** [comment]
I'd say a single dictionary, would make sense if gui ever goes to mobile.

for illustration:

    {
    "open_orders" : { "buy" : [(0.022, 0.5), (0.018, 1.5) ],
                            "sell"  : [(0.027, 0.5), (0.033,1.5) ]},
    "filled_orders" :  {"buy" : [(0.022, 0.5, DD-MM-YY_HH:MM:SS), (0.018, 1.5, DD-MM-YY_HH:MM:SS) ],
                            "sell"  : [(0.027, 0.5 ,DD-MM-YY_HH:MM:SS), (0.033,1.5, DD-MM-YY_HH:MM:SS) ]},                          
    "balances" : {"BTC" : 0.5121,
                     "XMR": 15.2039},
    "market" : (00.24,0.026),
    "price"  : 0.025
                        
    }
edit: formatting not my thing

**Comment by needmoney90** [comment]
We should be returning it now.

https://github.com/livinginformation/merkato/blob/master/merkato/merkato.py#L203
