### ISSUE TITLE
Add attribution

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#38]
@evdc @15chrjef @nasaWelder 

If you want to add yourselves to the contributors section in the readme, feel free.

**Comment by mark-antony1** [comment]
the "Authors" section? There is a link to all contributors with commit amounts.

**Comment by needmoney90** [comment]
Hm. Should I have a separate section for major contributors? Or just remove it. Im open to it, all three of you have contributed significantly.

**Comment by mark-antony1** [comment]
Either works. It is essentially a status and ownership demonstration. Either a tiered or flat model makes the most sense. For example, the tiered would look like
Creator: LivingInformation
Core Contributors: evdc, 15chrjef, nasaWelder

Or the flat model would have us all under a 'contributors' title.

**Comment by mark-antony1** [comment]
@livinginformation thoughts on the two approaches?

**Comment by needmoney90** [comment]
I'll go with the first model, will put it in now.
