### ISSUE TITLE
Anti market order logic at lower level

### ISSUE THREAD

**Issue by nasaWelder** [needmoney90/merkato#43]
I think merkato should delegate this logic.

Each exchange class should check for market order (¿¿optionally, but default True??) At lowest possible level inside buy/sell function. 

I think kraken api has it built in, where other exchanges might need to look before leap.

**Comment by needmoney90** [comment]
Ah, so in order to make a stateful change to a market, you need to pass a particular flag? Makes sense, would prevent accidents. Defaulting to limit orders is sane.

**Comment by needmoney90** [comment]
If I'm reading you right, the title would be better as 'Trade operations default to limit orders'.

**Comment by nasaWelder** [comment]
My main point was was cleaning up merkato to make it the idea guy and not the enforcer.

    Merkato.maintain_ladder()
        ...
            Merkato.create_relative_bid_latter()
            ...
                Self.exchange.buy(..., limit_only=True, raise_on_market=...)

I'm not sure if it should raise or skip...

**Comment by mark-antony1** [comment]
Are there any use cases for market orders? If not, we should only allow limits via the exchanges interface or if the exchange does not provide an interface we will do the logic ourselves. This should be done at the class level for the specific exchange.

**Comment by nasaWelder** [comment]
We could make a fomo bot /s

Sounds like we all agree

**Comment by needmoney90** [comment]
If we add general trading features, market orders would be a needed feature. There are plenty of trading bots though, i'm not sure we need to reinvent the wheel. Where do you guys think our scope should be?

**Comment by nasaWelder** [comment]
Don't kill me: I was thinking about a liquidate to Fiat feature, it would have to be bullet proof though.

**Comment by needmoney90** [comment]
> Don't kill me

The code is GPL'd, if I don't add a useful feature, someone else will. If there is useful (within scope) functionality to add, I'm open to it.

**Comment by mark-antony1** [comment]
Prefer we iterate on with very high focus, make sure each feature is dynamite. Starting with basic ladder setup and maintenance seems like a good place to start with a single exchange.

**Comment by mark-antony1** [comment]
Is this done @nasaWelder @livinginformation ?

**Comment by nasaWelder** [comment]
Not done. Should only be moving a few lines of code.

**Comment by nasaWelder** [comment]
Should it instead be more strict? I.e. don't place an ask below lowest ask, instead of highest bid? Otherwise you'd be underbidding yourself

**Comment by needmoney90** [comment]
To market make and place bid/ask ladders, you need to sometimes place orders within the spread. I can't see any benefit to even optional strictness there.

Edit: if you mean "dont place orders if theres a gap in order to mazimize revenue", that ignores cross-exchange arbitrage

**Comment by nasaWelder** [comment]
I guess I'm missing some higher level understanding.

 I was thinking if the price is at 145 and I have an ask at 150, placing an ask in the gap at 130 is underbidding yourself.

**Comment by needmoney90** [comment]
Discord?
