### ISSUE TITLE
Ticker Standardization for Exchange Agnostic Instatiation

### ISSUE THREAD

**Issue by nasaWelder** [needmoney90/merkato#47]
As a (GUI) user, I'd like to supply Alt and Base coins separately (explicitly).

Tux exchange tickers look backwards, and the different exchanges use different schemes.

Can we have Merkato() accept this: Merkato(..., ..., alt="LTC", base="BTC")

the interface level would translate to the specific exchange ticker ID > "BTC_LTC"

**Comment by nasaWelder** [comment]
OR do you want selecting the exchange to dynamically change choices in ticker box. I think explicit is better IMHO

**Comment by needmoney90** [comment]
Explicit is definitely better, especially with polo offering non-btc base pairs. Future proofing like this is the smart thing to do.

**Comment by needmoney90** [comment]
Defining it explicitly cleans up some of my comment header syntax as well. Needing to specify BTC_XYX or XYZ for each operation was unwieldy. Definitely approve of the change.

**Comment by evdc** [comment]
👍
