### ISSUE TITLE
Formalize 'Distribution Strategies'

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#5]

**Comment by needmoney90** [comment]
Two strategy types, fixed range and continuous.

**Comment by needmoney90** [comment]
Fixed range is currently integrated, based on user specified parameters.

**Comment by nasaWelder** [comment]
Do you want to like use an equation to make profile? Either way it will have to be quantized to look like the current profiles... Right?

**Comment by needmoney90** [comment]
Im still figuring out how I want to do it, this is more my scratchpad of thoughts for the moment. Im thinking an equation is the only way it can be done for continuous distributions, but i'm puzzling over it.

**Comment by nasaWelder** [comment]
I think numpy is going to be bundled with the GUI. Assume uniform percentage profile array for input, then this would convert to allocation.

Iirc, it's element-wise and in-place

https://docs.scipy.org/doc/numpy/reference/generated/numpy.exp.html

**Comment by needmoney90** [comment]
Wait, why does the GUI need to know about the particular values of the distribution strategy? In theory the strategy is used to place orders on initialization, and the orderbook is sent to the GUI. Im not seeing where visualizing the strategy itself will be useful/wanted?

**Comment by nasaWelder** [comment]
To fine tune it, you'll see strategy overlaid on price chart.

**Comment by nasaWelder** [comment]
And I thought the GUI was going to initialize the merkato instance based on user input (prepopulated with config from db, and for reboot, it can be started automatically.

**Comment by needmoney90** [comment]
Yeah, the 'user input' path is the fixed range strategy type. The second type, continuous, is what i'm figuring out right now. Dont worry about continuous for now in the GUI, just build it out for fixed range.

**Comment by nasaWelder** [comment]
@livinginformation after our talk, I just realized how awesome the original method was. Since it +/- the entire spread opposite each close, it ratchets up with the price. Mind blown. FML lol

I thought it was supposed to stay in same absolute price range, and ratcheting was unsolved problem. (Not something I even tried to address)

**Comment by needmoney90** [comment]
:) The functionality falls out of maintaining the window, it's quite a neat strategy

**Comment by nasaWelder** [comment]
discussion / drawing of continuous ladder:

https://imgur.com/a/xmgos8U

summary: continuous, **_infinite_** ladder not possible because infinite budget needed at beginning,
however I show how to make a continuous, **_finite_** ladder in python. 

if we programmatically add profit to edge of ladder, we could probably do infinite.
we'd need a way to "define" in python what profit is, and how to identify/quantify it.

**Comment by needmoney90** [comment]
A geometric progression (1/2 + 1/4 + 1/8 + 1/16...) where at each level half your remaining balance is allocated, should work (as one example of a continuous distribution). 

The limit with n=2 as n approaches infinity of sum(1/n) is 1 (finite) 

Allocating profits to the tail only works if you can guarantee a non-trending market, which isn't really a guarantee.

**Comment by nasaWelder** [comment]
@livinginformation interesting, been about a decade since discussed limts. Do you have a link with the full equation?

I'm not sure I understand why profits are unsafe at edge of ladder during trending market...
they'd be sitting on the sidelines, correct? If they were added to tail, it would be as if they were there all along, I think.

**Comment by nasaWelder** [comment]
I found this, for hypothetical budget of 30, if anyone want's to see a type of infinite series with finite sum.
I'm guessing we'll hit a limit of minimum order size..

https://www.symbolab.com/solver/limit-of-sum-calculator/%5Clim_%7Bn%5Cto%5Cinfty%7D%5Cleft(%5Csum_%7Bi%3D1%7D%5E%7Bn%7D%5Cleft(%5Cfrac%7B30%7D%7Bn%7D%5Cright)%5Cright)

**Comment by needmoney90** [comment]
The minimum order sizes are generally bounded by the BTC amount as the price rises, so there should be no issues with minimum order sizes as it scales up.

**Comment by needmoney90** [comment]
On your symbolab solver, I'm speaking of the equation 

![\lim _{n\to \infty }\left(\sum _{i=2}^n\left(\frac{1}{n}\right)\right) = 1](https://latex.codecogs.com/gif.latex?\lim&space;_{n\to&space;\infty&space;}\left(\sum&space;_{i=2}^n\left(\frac{1}{n}\right)\right)&space;=&space;1)

 where the 1 on top represents 100% of your balance.

**Comment by needmoney90** [comment]
The geometric progression like that has been what I've referred to as 'distribution strategy 1', it was (in my opinion) the simplest way of using all funds but also going to a theoretically infinite price. There are potentially other viable strategies.

**Comment by needmoney90** [comment]
> I'm not sure I understand why profits are unsafe at edge of ladder during trending market...
they'd be sitting on the sidelines, correct? If they were added to tail, it would be as if they were there all along, I think.

The problem is that it doesn't ensure there will be much (if any) coins on the tail when/if the price gets there. The amount, in a heavily trending market, could theoretically be zero. I want to ensure a 'useful' amount at every price, if possible.

**Comment by needmoney90** [comment]
Things relating to this issue were discussed in #56. The relevant formulas have been written:

![](https://i.imgur.com/Oxi2bzR.jpg)

![](https://i.imgur.com/CYWdlWq.jpg)

Where A is the total to distribute this doubling, and S is your chosen step (0.25% step means S=1.0025)

**Comment by needmoney90** [comment]
For now, we will have a single distribution strategy (this one), and it's been formalized. That should close this issue.
