### ISSUE TITLE
Talk to discuss stuff

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#52]
@evdc @15chrjef @nasaWelder Let's discuss structure some time. When are you free?

We can use the Monero discord: https://discord.gg/XVKK6hX

**Comment by evdc** [comment]
At work ~9-5 and a friend's visiting after that so we'll see, but I'll try to get on if there's a time in the evening when everyone is free, or, Wednesday.

**Comment by nasaWelder** [comment]
I'm free all day during the week, except 7pm to 11pm ET (Florida Time Zone). I'd need advanced notice usually,though.

**Comment by mark-antony1** [comment]
Can this be closed @livinginformation

**Comment by needmoney90** [comment]
Yup, we have contact now.
