### ISSUE TITLE
Configuration storage location

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#59]
Should configurations be stored in the database, or in a file (portable)? I guess the sqlite db is as portable as a file. I'm leaning towards storing them in the db.

**Comment by mark-antony1** [comment]
I currently have it being saved to a file, should be fine as long as it stored somewhere in disk. Can return to later if need be.

**Comment by mark-antony1** [comment]
Is this settled @livinginformation ?

**Comment by nasaWelder** [comment]
Wouldn't file be easier to edit by hand, let's say if keys change? Or will it be encrypted db? I'm a DB noob, just hoping making changes easy

**Comment by mark-antony1** [comment]
It would be easier to edit by hand for the purpose of changing keys, but could potentially mess with the mutex piece of it. The CLI method allows one to update parameters so changing keys should be able to be done via that.

**Comment by needmoney90** [comment]
This should be fine for now, we can reopen another issue if need be.
