### ISSUE TITLE
Add API key validation on configuration creation

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#6]

**Comment by needmoney90** [comment]
We can use the getmyaddresses command for tux for testing. 

So, we have two choices: We can either validate that the public/private API keypair are a valid keypair via cryptography locally, or we can validate them by performing an authenticated command on tuxexchange (getmyaddresses). The second, if successful, will guarantee that the credentials are valid for a user on the exchange. The first will only guarantee that they're cryptographically valid. Which is preferable? @evdc @nasaWelder @15chrjef

**Comment by nasaWelder** [comment]
At the very least, need to "catch" the API response on a bad key. Other rejection responses too.
