### ISSUE TITLE
Add reboot functionality

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#65]
From discussion with @nasaWelder, this is a priority

**Comment by mark-antony1** [comment]
Does additional data need to be stored? If not, dosen't load_config cover this?

**Comment by nasaWelder** [comment]
Configuration doesn't currently store ticker info. I think you're right that that should cover it though.

We need two configs, exchange/API "profile", and a config that uses a profile and ticker.

Same profile used in several configs. 

I think this would help reboot and persistence. You'd need to be able to reconstruct the mutex "ID" from this info which is probably trivial.

**Comment by mark-antony1** [comment]
Can you give a json example of what the two configs might look like?

**Comment by needmoney90** [comment]
Well, the 'two configs' idea is probably because of DRY, we don't need to have the API keys + pair for every single merkato instance, as that would have duplicate API keys. So really we want an API key file, and then another file that contains the pair information (which is already stored in the mutex)

I propose we just check the mutex table to figure out what bots are active, as they contain their corresponding pairs and exchanges, and use the given exchange to access the respective API key config file. Then we don't need two configs (and the second config would just be implementing what we already have in the mutex table).

**Comment by mark-antony1** [comment]
1. You mentioned two seperate files, do you mean two seperate tables?
2. How does the mutex table know what is active?

**Comment by needmoney90** [comment]
No, I'm referring to what nasa is talking about.

I would like 1 config file for each exchange containing API keys, and every mutex in the mutexes table references a particular exchange config. Every mutex refers to an active Merkato, so on reboot we can just query the Mutexes table to find out which Merkatos to instantiate.

**Comment by needmoney90** [comment]
If an entry is in the mutexes table, it is assumed that it refers to an active market making instance that has orders on the books.

We will need to add a field to the mutex that references the ID of the last known order executed before the bot was last run.

**Comment by needmoney90** [comment]
Ah, it appears we are referring to the last_order field already in update mutex, it needs to be added to the table initialization.

**Comment by mark-antony1** [comment]
The table is does have a last_order field on initialization.  c.execute('''CREATE TABLE IF NOT EXISTS mutexes (exchange text, exchange_pair text, pair text, spread text, profit_limit integer, last_order text)''')

**Comment by nasaWelder** [comment]
Easiest thing for the GUI would be a function that returns a list of instantiated merkato instances. 

OR

A list of dictionaries, where the dictionaries are the "args":vals I could directly **kwarg to a merkato instance.

    for kwargs in fetch_current_merkatos():
        simple_app.add(Merkato(**kwargs))

**Comment by nasaWelder** [comment]
@livinginformation sounds like you'll need three tables to make a many to many relationship with API keys and mutex.

http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#Many-to-many

**Comment by mark-antony1** [comment]
Shouldn't be that hard to return the list of merkato instances. Anything that is stored in the DB can be retrieved in an array like format.

**Comment by mark-antony1** [comment]
Im not sure we need three tables, what tables are you thinking of @nasaWelder? What fields would they have?

**Comment by nasaWelder** [comment]
From the link above on many to many:


    db.define_table('config',
                    Field('exchange'),
                    Field('privkey'),
                    Field('publickey'),)

    db.define_table('mutex',
                    Field('exchange'),
                    Field('coin'),
                    Field('base'),)

    db.define_table('merkato',
                    Field('config', 'reference config'),
                    Field('mutex', 'reference mutex'))

**Comment by mark-antony1** [comment]
Ok and in this proposal would a merkato object have many mutexes and config files associated with it? My understanding is that a merkato object would have only one config and mutex associated with it.
@livinginformation do you have an opinion?

**Comment by needmoney90** [comment]
It looks like he's converted the config files to a config table, which I'm not opposed to. I could go either way, but standardizing on DB only instead of configs is probably the cleaner way to do it. I'm fine with a config table, mutex table, and a many to many join table for merkatos.

**Comment by needmoney90** [comment]
So, a merkato would be a combination of a config credential, and a mutex.

**Comment by mark-antony1** [comment]
Let's chat about this, when are you guys free today?

**Comment by mark-antony1** [comment]
is this now complete?

**Comment by needmoney90** [comment]
let me hop in discord, let me know when you're on

**Comment by needmoney90** [comment]
I don't think we have a merkato init function that lets us recover from the db yet (even if all the building blocks are there)

**Comment by needmoney90** [comment]
Should be added in #74
