### ISSUE TITLE
DB query to get all active merkatos in the database

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#69]

**Comment by nasaWelder** [comment]
from reboot issue:

> Easiest thing for the GUI would be a function that returns a list of instantiated merkato instances. 

> OR

> A list of dictionaries, where the dictionaries are the "args":vals I could directly **kwarg to a merkato instance.

    for kwargs in fetch_current_merkatos():
        simple_app.add(Merkato(**kwargs))

**Comment by mark-antony1** [comment]
This should be complete with the last commit
