### ISSUE TITLE
Create a mock exchange for testing without putting funds at risk

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#76]
For testing purposes, we'll want a mock exchange that can build an orderbook and execute orders.

Don't prioritize until after beta.

**Comment by nasaWelder** [comment]
GUI needs this sooner rather than later so I can test how the data is ingested by the graph. This will also force us to "normalize" the formats/data-stuctures returned between exchanges so the GUI can expect the same data structure every time.

**Comment by nasaWelder** [comment]
In fact, i think GUI is dependent on this. I can't reasonable test the interface with live money.

**Comment by needmoney90** [comment]
Ah, of course. Okay, we'll make this a requirement for beta then.

**Comment by needmoney90** [comment]
Alright, I'm going to settle into working on this for a couple hours. Need to nail down a sane structure. If anyone is around to talk high-level stuff, I'll be on Discord.

**Comment by needmoney90** [comment]
https://docs.google.com/document/d/1X0yDzu2xl3lEZh1SOIQSs7ey9NRHh5s5ZdRMjZvsBLY/edit?usp=sharing will contain a live view into the working specification, going to put anything that comes to mind there.

**Comment by nasaWelder** [comment]
I had started an attempt a few weeks ago. Basically a copy paste of a tux exchange object with added machinery for generating new price, checking that against self order book. You'd just need to replace _buy _sell and generate some of the data asked for in some of the other methods. Also see Graph.fake_data() in simple app for a very dumb version. That is at the merkato level though, so too abstract

**Comment by needmoney90** [comment]
#82 should take care of a chunk of this, we still need to hook the interface up to use the mock exchange (create signed request will need to actually talk to the orderbook)

**Comment by livinginformation** [comment]
Or the commands themselves could just be directly tied in and we remove the signed request part. Not sure if we want to go for clarity or keep the internal structure similar to the other exchanges.

**Comment by nasaWelder** [comment]
Nothing external calls signed request, I don't think we're simulating failed API calls, unless you wanna go full real life sim

**Comment by needmoney90** [comment]
[Project scope intensifies]

**Comment by needmoney90** [comment]
Yeah, lets keep it as lightweight as possible, we can nuke signed requests and stuff.

**Comment by nasaWelder** [comment]
I'll eventually bolt on a price determination override to be able to back test bots of different parameters against same price action. Like a list of price/time tuples arg

**Comment by needmoney90** [comment]
Ive been thinking the same thing (passing in time-series data of price over a span, and calculating the expected profit).

Ill add it as its own issue.

**Comment by mark-antony1** [comment]
is this complete @livinginformation @nasaWelder

**Comment by needmoney90** [comment]
Looks like it
