### ISSUE TITLE
Add persistence

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#8]

**Comment by needmoney90** [comment]
Currently if the bot crashes, a manual recovery needs to be performed. Persistence in the case of bot crash or network failure is a necessary feature before Merkato can go into Beta.

**Comment by nasaWelder** [comment]
I could make simple_app accept a list of dictionaries, to restart window monitoring. Or perhaps a cli arg with json object 🤔💭

**Comment by mark-antony1** [comment]
Is this complete with the sqlite set up? Reboot #65 should cover the additional points, correct?

**Comment by needmoney90** [comment]
Yes, rebooting will cover persistence. We can close this as a duplicate, that covers it better.
