### ISSUE TITLE
Add functions to flesh out test exchange

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#86]
Account creation (unauthenticated) with starting balances

Get trade history of a particular user ID

Will add more as they come to mind

**Comment by nasaWelder** [comment]
If y'all wanna go off the deep end even further, test exchange to have a mode that uses live data, with actual API calls, but maintains local fake order book

**Comment by needmoney90** [comment]
We aren't going off the deep end, this is as bare bones as is necessary for what we're doing. @15chrjef and I have been discussing this over telegram. We'll add more functionality like that once the bot is actually working, it's not necessary for the moment.

**Comment by needmoney90** [comment]
What format do you need bids/asks in to display the user's orderbook in the GUI?

**Comment by nasaWelder** [comment]
/s

Right now I'm just displaying lowest ask and highest bid. See top of simple app for spec

**Comment by needmoney90** [comment]
If you could set up a way to display the whole cumulative orderbook (or at least within a reasonable amount of the price), that would do wonders. Bid/ask depth, not just the highest order.

**Comment by nasaWelder** [comment]
I could add some sub plots or a text table. 
Could you draw an example?

Thought about adding tabs, so extra data would be behind the graphs, and logs.

**Comment by needmoney90** [comment]
> example

https://i.imgur.com/NPH9CBo.jpg

**Comment by nasaWelder** [comment]
What'd I miss? Are we making an exchange, all vs XMR? :)

**Comment by needmoney90** [comment]
Nah, the test exchange will trade only btc/test, and will be much less efficient than normal exchanges. It's already basically working.

**Comment by needmoney90** [comment]
We need a way to be fed a list of bids and asks, and display a bid/ask depth (like the above image)

**Comment by nasaWelder** [comment]
I know how to display it, I need a list of bid tuples (price, amout)

And one for asks.

Then I'll split them up to work in:

https://matplotlib.org/1.2.1/examples/pylab_examples/histogram_demo.html

**Comment by mark-antony1** [comment]
@livinginformation it could be fed in directly on inititialization, and then constantly modified with additional bids/asks.

**Comment by needmoney90** [comment]
Nasa: Does the histogram let you do cumulative graphs? You can just add the sum of all the prior orders I guess, but i'm curious if theres an explicit function for it.

@15chrjef so we pass in two arrays of bid/ask tuples, and then when new orders are placed, feed the both arrays back in and recompute the depth charts?

**Comment by needmoney90** [comment]
I was trying to think of a way to do it with just the delta, but that's not really necessary if we aren't worried about efficiency

**Comment by nasaWelder** [comment]
I could append Delta and redraw. Easy. 

We might need to worry about efficiency soon. It's very serial right now, what frequency do we need to update order book?

**Comment by needmoney90** [comment]
I think doing it without the delta will work fine, if we end up needing efficiency we can optimize later. For now just assume reinitializing/redrawing the entire orderbooks every time.

For the test exchange, we'll update orderbook after a series of buys or sells (I've got some ideas of how to simulate market activity)

**Comment by mark-antony1** [comment]
you would only pass the arrays in on initialization

**Comment by needmoney90** [comment]
How do we account for removing orders using deltas when they're hit? I guess we could just pop them.

**Comment by nasaWelder** [comment]
Matplotlib just draws whatever is in pair of lists. Pop and append as you like. Id have to maintain a list of tuples then Regen the separate lists each time, though

**Comment by mark-antony1** [comment]
is this complete @livinginformation @nasaWelder

**Comment by needmoney90** [comment]
Think so.

**Comment by nasaWelder** [comment]
@livinginfotmation
I think we're missing balance enforcement. This isn't a simple problem because usually we won't want persistence when launching a test exchange. 

We need a way to set initial balances and then double entry account for the deltas as orders get closed

**Comment by nasaWelder** [comment]
I think we need a Merkato sub class or logic that doesn't touch  the DB when a test exchange is used, or only if you really want to.
