### ISSUE TITLE
Add Binance support

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#9]

**Comment by mark-antony1** [comment]
This is should be implemented before Polo and Bitr since it offers the greatest quantity of assets.

**Comment by needmoney90** [comment]
I dont have funds there, but I can look into making an account. How are they on KYC/AML?

**Comment by mark-antony1** [comment]
email only unlimited deposits, 2BTC/day withdrawl limit.

**Comment by nasaWelder** [comment]
EXCHANGE_MAX_NUM_ORDERS

The MAX_NUM_ORDERS filter defines the maximum number of orders an account is allowed to have open on the exchange. Note that both "algo" orders and normal orders are counted for this filter.

/exchangeInfo format:

  {
    "filterType": "EXCHANGE_MAX_NUM_ORDERS",
    "limit": 1000
  }

from https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by needmoney90** [comment]
This should be complete.
