### ISSUE TITLE
GUI Crash

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#93]
Traceback (most recent call last):
  File "simple_app.py", line 854, in <module>
    root.mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1280, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by needmoney90** [comment]
It appears to happen when I scroll to the bottom of the list of pairs on the right-hand side

**Comment by nasaWelder** [comment]
Ouch, every time?

**Comment by needmoney90** [comment]
Yessir

**Comment by nasaWelder** [comment]
Mouse Scroll wheel or button on slider?

**Comment by needmoney90** [comment]
It can be recreated on my end by mousing over the scrollbar on the far right, and scrolling until the bottom (at which point that error occurs)

**Comment by needmoney90** [comment]
Still crashes with the updated code

**Comment by needmoney90** [comment]
Traceback (most recent call last):
  File "simple_app.py", line 868, in <module>
    root.mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1280, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by needmoney90** [comment]
the error is now in line 868, so something changed

**Comment by nasaWelder** [comment]
I can't even recreate original crash. My fix disables scrolling altogether on my end. What python are you using?

**Comment by needmoney90** [comment]
python 3.6.5

**Comment by needmoney90** [comment]
<img width="1440" alt="screen shot 2018-05-20 at 6 47 43 pm" src="https://user-images.githubusercontent.com/3836500/40286823-57631c16-5c5e-11e8-8548-62d76c390c75.png">

**Comment by needmoney90** [comment]
![thing](https://user-images.githubusercontent.com/3836500/40286886-b069ae88-5c5e-11e8-9076-491064da57c2.png)

**Comment by needmoney90** [comment]
(from the first picture, looks like scrolling still exists for me)

**Comment by nasaWelder** [comment]
Can you try changing all references of "Button-4" to "Mousewheel" or "MouseWheel"? See if that does it for you.

**Comment by nasaWelder** [comment]
I meant I disabled scroll wheel actions. Is that not the cause?

**Comment by needmoney90** [comment]
On my way to the airport at the moment, I'll try when I get the chance.

**Comment by nasaWelder** [comment]
Do you not get the performance on the buttons themselves? It shows it for me

**Comment by nasaWelder** [comment]
Clue https://mail.python.org/pipermail/matplotlib-users/2017-January/000728.html

**Comment by nasaWelder** [comment]
Workarounds
https://github.com/matplotlib/matplotlib/issues/9637

**Comment by needmoney90** [comment]
```
  try:
    plt.show()
  except UnicodeDecodeError:
    continue
  break
```
I'm shuddering so hard right now

**Comment by needmoney90** [comment]
If it works it works, patch it and I'll hold my nose

**Comment by nasaWelder** [comment]
the official way to turn off scroll wheel for other widgets (not the plots) is to overwrite the binding to return "break" as a string. I'm sure that gets eval'd. (shrug)

I think a cleaner way (from first link):

    def process_scroll(event):
        pass

    fig.canvas.mpl_connect('scroll_event', process_scroll)
