### ISSUE TITLE
Add GUI pane for orderbook depth

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#94]
The user should, in addition to being able to see the price chart with their highest bid / lowest ask, also be able to see the orderbook depth (within reasonable distance of the current price). This can either be it's own pane, or displayed adjacent to the price chart.

**Comment by nasaWelder** [comment]
this is what I have so far:
![screenshot at 2018-05-22 23 28 35](https://user-images.githubusercontent.com/33912627/40405004-ebfac968-5e17-11e8-8cd4-ca6b0e37b616.png)

is that enough?
this online example is more sophisticated but I need to understand it first:
![output_36_0](https://user-images.githubusercontent.com/33912627/40405047-20e3ac62-5e18-11e8-8ad7-3dfaf8a7afe4.png)
 It's from http://rickyhan.com/jekyll/update/2017/09/24/visualizing-order-book.html

**Comment by needmoney90** [comment]
It will do for now, the second is obviously nicer

**Comment by nasaWelder** [comment]
Implemented. Close this.
