### ISSUE TITLE
Fix bug in GUI price chart

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#95]
The GUI's markers for where the price intersects the user's bids and asks are offset, and appear to sometimes trigger when no intersection occurred

**Comment by needmoney90** [comment]
When the price intersects with the orderbook, only show the effects on the user's bids/asks in the next time interval (not the same interval it occurred in). I believe that's the issue, it should be offset by one unit in time.

**Comment by nasaWelder** [comment]
This isn't a bug. The offset is hardcoded in the fake data generation. It's not worth making better with real fake exchange in the pipeline.

**Comment by nasaWelder** [comment]
The real order will have real time, so will be placed exactly. I didn't simulate that much resolution

**Comment by needmoney90** [comment]
Great, closing the issue
