### ISSUE TITLE
Update functions in test exchange

### ISSUE THREAD

**Issue by needmoney90** [needmoney90/merkato#96]
Same as #86. 

get_my_open_orders():
https://github.com/livinginformation/merkato/blob/master/merkato/exchanges/test_exchange/exchange.py#L99

get_all_orders():
Done

Both need to pass data back to the GUI.

**Comment by nasaWelder** [comment]
To clarify the GUI gets this info from merkato as middleman

**Comment by needmoney90** [comment]
You should be able to run merkato.exchange.get_all_orders(). I can expose a function on the Merkato itself if you want though.

**Comment by nasaWelder** [comment]
I figured it's simplest to get it as return info from update_order_book since that info is used therein anyways

**Comment by needmoney90** [comment]
ah, I can do that. One second.

**Comment by needmoney90** [comment]
Done, context contains orderbook now. I'm not sure if its formatted how we want yet, but you should be able to access it.

**Comment by needmoney90** [comment]
https://github.com/livinginformation/merkato/blob/master/merkato/merkato.py#L347

get_my_open_orders may be broken at the moment, let me know if something errors.

**Comment by needmoney90** [comment]
get_my_open_orders returns a blank string now, to prevent errors. Can fill it in once we've got the entire orderbook worked out.

**Comment by mark-antony1** [comment]
not horrible, just have to filter and merge both the bids and asks in the orderbook by user_id

**Comment by mark-antony1** [comment]
Does this satisfy the criteria @livinginformation @nasaWelder ?

**Comment by needmoney90** [comment]
I believe it does
